version: '3'

services:
  postgres:
    container_name: uni-db
    restart: unless-stopped
    image: postgres:17-alpine
    env_file:
      - ".prod.env"
    ports:
      - "5432:5432"
    volumes:
      - ./uni-data/postgres:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    container_name: uni-backend
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ".prod.env"
    networks:
      - backend-network
    depends_on:
      - postgres
  

networks:
  backend-network:
    driver: bridge

