version: '3'

services:
  postgres:
    container_name: uni-db
    restart: unless-stopped
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./uni-data/postgres:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    container_name: uni-backend
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=${APP_PORT}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL}
      - APP_IS_DEBUG=${APP_IS_DEBUG}
      - APP_PASSWORD_SALT=${APP_PASSWORD_SALT}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_ACCESS_TOKEN_LIFETIME=${JWT_ACCESS_TOKEN_LIFETIME}
      - JWT_REFRESH_TOKEN_LIFETIME=${JWT_REFRESH_TOKEN_LIFETIME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
    networks:
      - backend-network
    depends_on:
      - postgres
  

networks:
  backend-network:
    driver: bridge

