
### Auth Login
POST {{base}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Auth Register
POST {{base}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Auth Refrest token
POST {{base}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjc1NTgxNzksImlhdCI6MTcyNzM4NTM3OSwiaXNzIjoidW5pLXNjaGVkdWxlLWRldiIsIm5iZiI6MTcyNzM4NTM3OSwic3ViIjoiNCJ9.RmV8BhtvKcq0esK1CbWxAHUlyHcmyqAdh9hStpquIKg"
}

### Schedule Create schedule
POST {{base}}/api/v1/schedule
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Test Schedule",
  "slug": "test",
  "creator_id": 10
}

### Schedule Get schedule by slug
GET {{base}}/api/v1/schedule/slug/test
Authorization: Bearer {{token}}


### Schedule Create teacher
POST {{base}}/api/v1/teacher
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "short_name": "Марков А. К."
}

### Lesson Create lesson
POST {{base}}/api/v1/lesson
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Lesson 3",
  "location": "Gym",
  "teacher_id": 2,
  "lesson_type": 2
}

### Schedule Add slot
POST {{base}}/api/v1/schedule/1/slot
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "weekday": 4,
  "number": 1,
  "is_alternating": true,
  "even_week_lesson_id": 1,
  "odd_week_lesson_id": 3
}