
### Auth Login
POST {{base}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Auth Register
POST {{base}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Auth Refrest token
POST {{base}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjc1NTgxNzksImlhdCI6MTcyNzM4NTM3OSwiaXNzIjoidW5pLXNjaGVkdWxlLWRldiIsIm5iZiI6MTcyNzM4NTM3OSwic3ViIjoiNCJ9.RmV8BhtvKcq0esK1CbWxAHUlyHcmyqAdh9hStpquIKg"
}

### Schedule Create schedule
POST {{base}}/api/v1/schedules
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "slug": "test-schedule"
}


### Schedule Get schedule by slug
GET {{base}}/api/v1/schedules/slug/test-schedule
Authorization: Bearer {{token}}


### Schedule Get schedule by id
GET {{base}}/api/v1/schedule/slug/test
Authorization: Bearer {{token}}

### Schedule Create teacher
POST {{base}}/api/v1/teacher
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "short_name": "Марков А. К."
}

### Lesson Create lesson
POST {{base}}/api/v1/lesson
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Lesson 3",
  "location": "Gym",
  "teacher_id": 2,
  "lesson_type": 2
}

### Schedule Add slot
POST {{base}}/api/v1/schedule/1/slot
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "weekday": 4,
  "number": 1,
  "is_alternating": true,
  "even_week_lesson_id": 1,
  "odd_week_lesson_id": 3
}

### Teacher Add
POST {{base}}/api/v1/teachers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Дмитрий",
  "last_name": "Саратов",
  "surname": "Михаилович",
  "schedule_id": 1
}

### Teacher Get All
GET {{base}}/api/v1/schedules/1/teachers
Content-Type: application/json
Authorization: Bearer {{token}}


### Subject Add
POST {{base}}/api/v1/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Алгебра",
  "schedule_id": 1
}

### Subject Get All
GET {{base}}/api/v1/schedules/1/subjects
Content-Type: application/json
Authorization: Bearer {{token}}


### Class Add
POST {{base}}/api/v1/classes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "schedule_id": 1,
  "subject_id": 2,
  "teacher_id": 3,
  "class_type": "lab"
}

### Class Get All
GET {{base}}/api/v1/schedules/1/classes
Content-Type: application/json
Authorization: Bearer {{token}}

### Entry Add
POST {{base}}/api/v1/schedules/test-schedule/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "day": "tuesday",
  "schedule_id": 1,
  "class_number": 4,
  "even_class_id": 7,
  "is_static": false
}
